package customstruct

type CustomStruct struct {
	Oui          string
	ManShortName string
	ManLongName  string
}

var ManufacturerList []CustomStruct

func ManList() []CustomStruct {
	ManufacturerList = []CustomStruct{
		{Oui: "00:01:31", ManShortName: "BoschSecurit", ManLongName: "Bosch Security Systems, Inc."},
		{Oui: "00:04:63", ManShortName: "BoschSecurit", ManLongName: "Bosch Security Systems"},
		{Oui: "00:07:5F", ManShortName: "VCSVideoComm", ManLongName: "VCS Video Communication Systems AG"},
		{Oui: "00:0F:12", ManShortName: "PanasonicEur", ManLongName: "Panasonic Europe Ltd."},
		{Oui: "00:12:67", ManShortName: "Panasonic", ManLongName: "Panasonic Corporation"},
		{Oui: "00:15:6D", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "00:19:87", ManShortName: "PanasonicMob", ManLongName: "Panasonic Mobile Communications Co.,Ltd."},
		{Oui: "00:1B:D3", ManShortName: "PanasonicAVC", ManLongName: "Panasonic Corporation AVC Networks Company"},
		{Oui: "00:20:D9", ManShortName: "PanasonicTec", ManLongName: "Panasonic Technologies, Inc./Mieco-Us"},
		{Oui: "00:24:A4", ManShortName: "SikluCommuni", ManLongName: "Siklu Communication"},
		{Oui: "00:27:22", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "00:40:8C", ManShortName: "AxisCommunic", ManLongName: "Axis Communications AB"},
		{Oui: "00:50:40", ManShortName: "PanasonicEle", ManLongName: "Panasonic Electric Works Co., Ltd."},
		{Oui: "00:50:C2:B0:40/36", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "00:50:C2:E9:80/36", ManShortName: "i3Internatio", ManLongName: "i3 International Inc."},
		{Oui: "00:80:F0", ManShortName: "PanasonicCom", ManLongName: "Panasonic Communications Co., Ltd."},
		{Oui: "00:BC:99", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "00:C0:8F", ManShortName: "PanasonicEle", ManLongName: "Panasonic Electric Works Co., Ltd."},
		{Oui: "00:D0:60", ManShortName: "PanasonicEur", ManLongName: "Panasonic Europe Ltd."},
		{Oui: "04:03:12", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "04:04:B8", ManShortName: "ChinaHualuPa", ManLongName: "China Hualu Panasonic AVC Networks Co., LTD."},
		{Oui: "04:18:D6", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "04:20:9A", ManShortName: "PanasonicAVC", ManLongName: "Panasonic Corporation AVC Networks Company"},
		{Oui: "04:EE:CD", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "08:00:23", ManShortName: "PanasonicCom", ManLongName: "Panasonic Communications Co., Ltd."},
		{Oui: "08:3B:C1", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "08:54:11", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "08:A1:89", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "08:CC:81", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "0C:65:9A", ManShortName: "PanasonicAut", ManLongName: "Panasonic Automotive Systems Company of America"},
		{Oui: "0C:75:D2", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "0C:EA:14", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "10:12:FB", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "18:68:CB", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "18:80:25", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "18:E8:29", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "18:F8:7A", ManShortName: "i3Internatio", ManLongName: "i3 International Inc."},
		{Oui: "1C:0B:8B", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "1C:6A:1B", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "20:0E:0F", ManShortName: "PanasonicMar", ManLongName: "Panasonic Marketing Middle East & Africa FZE"},
		{Oui: "20:B5:C6", ManShortName: "MimosaNetwor", ManLongName: "Mimosa Networks"},
		{Oui: "20:C6:EB", ManShortName: "PanasonicAVC", ManLongName: "Panasonic Corporation AVC Networks Company"},
		{Oui: "20:E5:9B", ManShortName: "PanasonicAut", ManLongName: "Panasonic Automotive Systems"},
		{Oui: "24:0F:9B", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "24:28:FD", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "24:32:AE", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "24:48:45", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "24:5A:4C", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "24:78:23", ManShortName: "PanasonicEnt", ManLongName: "Panasonic Entertainment & Communication Co., Ltd."},
		{Oui: "24:A4:3C", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "24:A8:7D", ManShortName: "PanasonicAut", ManLongName: "Panasonic Automotive Systems Asia Pacific(Thailand)Co.,Ltd."},
		{Oui: "24:B1:05", ManShortName: "PramaHikvisi", ManLongName: "Prama Hikvision India Private Limited"},
		{Oui: "28:36:38:10/28", ManShortName: "PanasonicSys", ManLongName: "Panasonic System Solutions Europe"},
		{Oui: "28:57:BE", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "28:70:4E", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "28:F8:C6:30/28", ManShortName: "PanasonicAut", ManLongName: "Panasonic Automotive System Malaysia"},
		{Oui: "2C:69:1D:A0/28", ManShortName: "PanasonicApp", ManLongName: "Panasonic Appliances Marketing Asia Pacific"},
		{Oui: "2C:A5:9C", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "30:4C:7E", ManShortName: "PanasonicEle", ManLongName: "Panasonic Electric Works Automation Controls Techno Co.,Ltd."},
		{Oui: "34:04:9E:A0/28", ManShortName: "i3Internatio", ManLongName: "i3 International Inc."},
		{Oui: "34:09:62", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "34:31:7F", ManShortName: "PanasonicApp", ManLongName: "Panasonic Appliances Company"},
		{Oui: "34:32:E6", ManShortName: "PanasonicInd", ManLongName: "Panasonic Industrial Devices Europe GmbH"},
		{Oui: "34:F6:D2", ManShortName: "PanasonicTai", ManLongName: "Panasonic Taiwan Co.,Ltd."},
		{Oui: "3C:1B:F8", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "3C:6F:EA", ManShortName: "PanasonicInd", ManLongName: "Panasonic India Pvt. Ltd."},
		{Oui: "40:AC:BF", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "44:19:B6", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "44:47:CC", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "44:A6:42", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "44:D9:E7", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "48:78:5B", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "4C:1F:86", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "4C:21:8C", ManShortName: "PanasonicInd", ManLongName: "Panasonic India Private limited"},
		{Oui: "4C:36:4E", ManShortName: "PanasonicCon", ManLongName: "Panasonic Connect Co., Ltd."},
		{Oui: "4C:62:DF", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "4C:BD:8F", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "4C:F5:DC", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "50:0B:91:80/28", ManShortName: "PanasonicEnt", ManLongName: "Panasonic Enterprise Solutions Company"},
		{Oui: "50:E5:38", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "50:FA:CB:90/28", ManShortName: "BoschSecurit", ManLongName: "Bosch Security Systems"},
		{Oui: "54:5B:86", ManShortName: "PanasonicAut", ManLongName: "Panasonic Automotive Systems Co.,Ltd"},
		{Oui: "54:8C:81", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "54:C4:15", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "54:CD:10", ManShortName: "PanasonicMob", ManLongName: "Panasonic Mobile Communications Co.,Ltd."},
		{Oui: "58:03:FB", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "58:50:ED", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "58:D6:1F", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "5C:34:5B", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "60:22:32", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "64:DB:8B", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "68:6D:BC", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "68:72:51", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "68:D7:9A", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "6C:63:F8", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "70:58:12", ManShortName: "PanasonicAVC", ManLongName: "Panasonic Corporation AVC Networks Company"},
		{Oui: "70:A7:41", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "70:B3:D5:EC:80/36", ManShortName: "PanasonicLif", ManLongName: "Panasonic Life Solutions Elektr?K Sanay? Ve T?Care"},
		{Oui: "74:3F:C2", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "74:83:C2", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "74:A5:7E", ManShortName: "PanasonicEco", ManLongName: "Panasonic Ecology Systems"},
		{Oui: "74:AC:B9", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "74:D7:CA", ManShortName: "PanasonicAut", ManLongName: "Panasonic Automotive Systems Co.,Ltd"},
		{Oui: "74:F9:2C", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "74:FA:29", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "78:45:58", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "78:8A:20", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "80:2A:A8", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "80:48:9F", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "80:7C:62", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "80:BE:AF", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "80:C7:55", ManShortName: "PanasonicApp", ManLongName: "Panasonic Appliances Company"},
		{Oui: "80:F5:AE", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "84:78:48", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "84:94:59", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "84:9A:40", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "84:9C:A4", ManShortName: "MimosaNetwor", ManLongName: "Mimosa Networks"},
		{Oui: "88:DE:39", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "8C:1F:64:2C:30/36", ManShortName: "TeraDiodePan", ManLongName: "TeraDiode / Panasonic"},
		{Oui: "8C:22:D2", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "8C:30:66", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "8C:B6:C5", ManShortName: "MimosaNetwor", ManLongName: "Mimosa Networks"},
		{Oui: "8C:C1:21", ManShortName: "PanasonicAVC", ManLongName: "Panasonic Corporation AVC Networks Company"},
		{Oui: "8C:E7:48", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "8C:ED:E1", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "90:41:B2", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "90:70:BF", ManShortName: "MimosaNetwor", ManLongName: "Mimosa Networks"},
		{Oui: "94:2A:6F", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "94:9D:57", ManShortName: "PanasonicdoB", ManLongName: "Panasonic do Brasil Limitada"},
		{Oui: "94:E1:AC", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "98:8B:0A", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "98:9D:E5", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "98:DF:82", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "98:F1:12", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "9C:05:D6", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "9C:61:1D", ManShortName: "PanasonicNor", ManLongName: "Panasonic Corporation of North America"},
		{Oui: "A0:FF:0C", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "A4:14:37", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "A4:29:02", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "A4:4B:D9", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "A4:A4:59", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "A4:D5:C2", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "A4:F8:FF", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "A8:13:74", ManShortName: "PanasonicAVC", ManLongName: "Panasonic Corporation AVC Networks Company"},
		{Oui: "A8:9C:6C", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "AC:8B:A9", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "AC:B9:2F", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "AC:CB:51", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "AC:CC:8E", ManShortName: "AxisCommunic", ManLongName: "Axis Communications AB"},
		{Oui: "B0:D8:88", ManShortName: "PanasonicAut", ManLongName: "Panasonic Automotive Systems Co.,Ltd"},
		{Oui: "B4:6C:47", ManShortName: "PanasonicApp", ManLongName: "Panasonic Appliances Company"},
		{Oui: "B4:A3:82", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "B4:FB:E4", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "B8:20:8E", ManShortName: "PanasonicCon", ManLongName: "Panasonic Connect Co., Ltd."},
		{Oui: "B8:A4:4F", ManShortName: "AxisCommunic", ManLongName: "Axis Communications AB"},
		{Oui: "BC:29:78", ManShortName: "PramaHikvisi", ManLongName: "Prama Hikvision India Private Limited"},
		{Oui: "BC:3E:0B", ManShortName: "PanasonicCon", ManLongName: "Panasonic Connect Co., Ltd."},
		{Oui: "BC:5E:33", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "BC:69:CB", ManShortName: "PanasonicEle", ManLongName: "Panasonic Electric Works Networks Co., Ltd."},
		{Oui: "BC:9B:5E", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "BC:AD:28", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "BC:BA:C2", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "BC:C3:42", ManShortName: "PanasonicCom", ManLongName: "Panasonic Communications Co., Ltd."},
		{Oui: "C0:51:7E", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "C0:56:E3", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "C0:6D:ED", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "C4:2F:90", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "C8:A7:02", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "CC:13:F3", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "CC:35:D9", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "CC:54:FE", ManShortName: "MimosaNetwor", ManLongName: "Mimosa Networks"},
		{Oui: "CC:57:63", ManShortName: "PanasonicAut", ManLongName: "Panasonic Automotive Systems Co.,Ltd"},
		{Oui: "CC:7E:E7", ManShortName: "PanasonicAVC", ManLongName: "Panasonic Corporation AVC Networks Company"},
		{Oui: "D0:21:F9", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "D4:2D:C5", ManShortName: "iPRO", ManLongName: "i-PRO Co., Ltd."},
		{Oui: "D4:89:C1", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "D4:E8:53", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "D8:AF:F1", ManShortName: "PanasonicApp", ManLongName: "Panasonic Appliances Company"},
		{Oui: "D8:B1:2A", ManShortName: "PanasonicMob", ManLongName: "Panasonic Mobile Communications Co.,Ltd."},
		{Oui: "D8:B3:70", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "DC:07:F8", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "DC:9F:DB", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "DC:D2:6A", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "E0:63:DA", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "E0:BA:AD", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "E0:CA:3C", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "E0:DF:13", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "E0:EE:1B", ManShortName: "PanasonicAut", ManLongName: "Panasonic Automotive Systems Company of America"},
		{Oui: "E4:38:83", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "E4:D5:8B", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "E8:27:25", ManShortName: "AxisCommunic", ManLongName: "Axis Communications AB"},
		{Oui: "E8:A0:ED", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "EC:65:CC", ManShortName: "PanasonicAut", ManLongName: "Panasonic Automotive Systems Company of America"},
		{Oui: "EC:A9:71", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "EC:C8:9C", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "F0:9F:C2", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "F4:92:BF", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "F4:E2:C6", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
		{Oui: "F8:4D:FC", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "FA:93:05", ManShortName: "PanasonicAut", ManLongName: "Panasonic Automotive Systems Co., Ltd."},
		{Oui: "FC:9F:FD", ManShortName: "HikvisionDig", ManLongName: "Hangzhou Hikvision Digital Technology Co.,Ltd."},
		{Oui: "FC:EC:DA", ManShortName: "Ubiquiti", ManLongName: "Ubiquiti Inc"},
	}
	return ManufacturerList

}
